---
title: "Untitled"
format: html
editor: visual
---

```{r}
data <- read.csv('dataset02.csv')
```

```{r}
head(data)
```

```{r}

m1<-glm(Total.Number.of.Family.members~Total.Household.Income+Total.Food.Expenditure+ Household.Head.Sex +Household.Head.Age+Type.of.Household +  House.Floor.Area +House.Age+ Number.of.bedrooms+Electricity,data=data , family =  poisson)


```

```{r}
summary(m1)
```

```{r}
m2<-glm(Total.Number.of.Family.members~Total.Household.Income+Total.Food.Expenditure+ Household.Head.Sex +Household.Head.Age+Type.of.Household  +House.Age+ Number.of.bedrooms+Electricity,data=data , family =  poisson)
summary(m2)
```

```{r}
m3 <- glm(Total.Number.of.Family.members~Total.Household.Income+Total.Food.Expenditure+ Household.Head.Sex +Household.Head.Age+Type.of.Household  +House.Age+ Number.of.bedrooms,data=data , family =  poisson)


summary(m3)
```

```{r}
m4 <- glm(Total.Number.of.Family.members~Total.Household.Income+Total.Food.Expenditure+ Household.Head.Sex +Household.Head.Age+Type.of.Household  +House.Age,data=data , family =  poisson)

summary(m4)
```

```{r}

m5 <- glm(Total.Number.of.Family.members~Total.Household.Income+Total.Food.Expenditure+ Household.Head.Sex +Household.Head.Age+Type.of.Household  + Number.of.bedrooms,data=data , family =  poisson)

summary(m5)
```

```{r}
m6 <- glm(Total.Number.of.Family.members~Total.Household.Income+Total.Food.Expenditure+ Household.Head.Sex +Household.Head.Age  +House.Age+ Number.of.bedrooms,data=data , family =  poisson)
summary(m6)
```

```{r}

m7 <- glm(Total.Number.of.Family.members~Total.Household.Income+Total.Food.Expenditure+ Household.Head.Sex +Type.of.Household  +House.Age+ Number.of.bedrooms,data=data , family =  poisson)
summary(m7)

```

```{r}
m8 <- glm(Total.Number.of.Family.members~Total.Household.Income+Total.Food.Expenditure +Household.Head.Age+Type.of.Household  +House.Age+ Number.of.bedrooms,data=data , family =  poisson)
summary(m8)
```

```{r}
m9<- glm(Total.Number.of.Family.members~Total.Household.Income+ Household.Head.Sex +Household.Head.Age+Type.of.Household  +House.Age+ Number.of.bedrooms,data=data , family =  poisson)
summary(m9)
```

```{r}
m10 <- glm(Total.Number.of.Family.members~Total.Food.Expenditure+ Household.Head.Sex +Household.Head.Age+Type.of.Household  +House.Age+ Number.of.bedrooms,data=data , family =  poisson)
summary(m10)
```

```{r}
#the final model is m3

```

```{r}



```
